---
#NAMESPACE
kind: Namespace
apiVersion: v1
metadata:
  name: postgresql
---
#CONFIG MAP 
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgresql
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---  
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: postgresql
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: postgresql
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# DEPLOYMENT
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: postgresql  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
#SERVICE
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql  
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres